apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-jet-configuration
  labels:
    app: hazelcast-jet
data:
  hazelcast.yaml: |-
    hazelcast:
      cluster-name: ${CLUSTER_NAME}
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            namespace: ${NAMESPACE}
            service-name: ${SERVICE_NAME}
        rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
