apiVersion: v1
kind: Service
metadata:
  name: hazelcast-jet-service-lb
  labels:
    app: hazelcast-jet
spec:
  type: LoadBalancer
  selector:
    app: hazelcast-jet
  ports:
  - protocol: TCP
    port: 5701
    nodePort: 30200
