apiVersion: v1
kind: Service
metadata:
  name: hazelcast-jet-service-nodeport
spec:
  type: NodePort
  selector:
    app: hazelcast-jet
    role: hazelcast-jet
  ports:
  - protocol: TCP
    port: 5701
    targetPort: 5701
    nodePort: 30210
