apiVersion: v1
kind: Service
metadata:
  name: hazelcast-jet-service-0
  labels:
    app: hazelcast-jet
    statefulset.kubernetes.io/pod-name: hazelcast-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: hazelcast-jet
    statefulset.kubernetes.io/pod-name: hazelcast-jet-0
  ports:
  - nodePort: 30201
    port: 5701
    protocol: TCP
    targetPort: jet
