apiVersion: v1
kind: Service
metadata:
  name: hazelcast-jet-service-nodeport-0
  labels:
    app: hazelcast-jet
    role: hazelcast-jet
    statefulset.kubernetes.io/pod-name: hazelcast-jet-0
spec:
  type: NodePort
  selector:
    app: hazelcast-jet
    role: hazelcast-jet
    statefulset.kubernetes.io/pod-name: hazelcast-jet-0
  ports:
  - nodePort: 30211
    port: 5701
    protocol: TCP
    targetPort: jet
