apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hazelcast-pv-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: hazelcast-pv-volume
