apiVersion: v1
kind: Pod
metadata:
  name: cephfs-pod
spec:
  volumes:
    - name: cephfs-storage
      persistentVolumeClaim:
        claimName: hazelcast-pv-claim
  containers:
    - name: app
      image: ubuntu

      # Mount the NFS volume in the container
      volumeMounts:
        - name: cephfs-storage
          mountPath: /var/cephfs

      # Write to a file inside our NFS
     # command: ["/bin/bash"]
      args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 5; done"]
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
