  ${SERVER_NAME}:
    image: padogrid/snappydata:${VERSION}
    hostname: ${SERVER_NAME}
    mem_limit: 1g
    depends_on:
     - locator
    expose:
     - "$CLIENT_PORT"
     - "$JMX_PORT"
     - "$DEBUG_PORT"
     - "$PROMETHEUS_PORT"
    ports:
     - "${HOST_CLIENT_PORT}:$CLIENT_PORT"
     - "${HOST_JMX_PORT}:$JMX_PORT"
     - "${HOST_DEBUG_PORT}:$DEBUG_PORT"
     - "${HOST_PROMETHEUS_PORT}:$PROMETHEUS_PORT"
    volumes:
     - ./padogrid:/padogrid/
    command:
      - bash
      - -c
      - |
        export LOG_FILE=/padogrid/log/`hostname`.log \
        && \
        start server -name=`hostname` -locators=locator:$LOCATOR_PORT -hostname-for-clients=$HOSTNAME_FOR_CLIENTS -classpath=/padogrid/plugins/*:/padogrid/lib/* -log-file=/padogrid/log/`hostname`.log -member-timeout=250000 -run-netserver=true -thrift-server-port=$CLIENT_PORT -spark.ui.port=$SPARK_UI_PORT -heap-size=$HEAP_SIZE -statistic-archive-file=/padogrid/stats/`hostname`.gfs -J-Dlog4j.configurationFile=/padogrid/etc/log4j2.properties -J-Xloggc:/padogrid/log/`hostname`-gc.log -J-XX:+PrintGCDetails -J-XX:+PrintGCDateStamps -J-DgemfirePropertyFile=/padogrid/etc/gemfirexd.properties -J-javaagent:/padogrid/lib/${PROMETHEUS_JAR}=$PROMETHEUS_PORT:/padogrid/etc/prometheus.yml -client-port=$CLIENT_PORT
    restart: on-failure
