apiVersion: v1
kind: PersistentVolume
metadata:
  name: hazelcast-pv-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/data/custom"

