apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hazelcast-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: hazelcast-pv-volume
