apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-release-geode
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: server
  minReplicas: 2
  maxReplicas: 10
#  targetCPUUtilizationPercentage: 80
  metrics:
  - type: Pods
    pods:
      metricName: on_heap_ratio
      targetAverageValue: 850m
