apiVersion: v1
kind: Service
metadata:
  name: locator
  namespace: default
spec:
  ports:
  - name: locator
    port: 10334
    protocol: TCP
    targetPort: 10334
  selector:
    app: locator
---
apiVersion: v1
kind: Service
metadata:
  name: locator-0
  namespace: default
spec:
  ports:
  - name: locator
    port: 10334
    nodePort: 30334
    protocol: TCP
    targetPort: 10334
  - name: pulse
    port: 7070
    nodePort: 30070
    protocol: TCP
    targetPort: 7070
  selector:
    app: locator
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: locator-1
  namespace: default
spec:
  ports:
  - name: locator
    port: 10334
    nodePort: 30335
    protocol: TCP
    targetPort: 10334
  - name: pulse
    port: 7070
    nodePort: 30071
    protocol: TCP
    targetPort: 7070
  selector:
    app: locator
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: locator
spec:
  selector:
    matchLabels:
      app: locator
  serviceName: "locator"
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: my-release
        app.kubernetes.io/name: geode-cluster
        app: locator
    spec:
      containers:
      - name: locator
        image: apachegeode/geode:latest
        command:
        - sh
        - -c
        - |
          gfsh start locator --name=$HOSTNAME \
              --locators=${LOCATOR_0_SERVICE_HOST}[${LOCATOR_0_SERVICE_PORT}],${LOCATOR_1_SERVICE_HOST}[${LOCATOR_1_SERVICE_PORT}]  \
              && \
          while true; do
            sleep 2
          done
        ports:
        - containerPort: 10334
          name: locator
          protocol: TCP
