apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: geode-cluster
  name: my-release-geode-metrics
  namespace: default
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    app: server
#    app.kubernetes.io/instance: my-release
#    app.kubernetes.io/name: geode-cluster
  sessionAffinity: None
  type: ClusterIP
