  ${SERVER_NAME}:
    env_file: .env
    environment:
      - JAVA_OPTS="-Dhazelcast-addon.management-center=http://$HOSTNAME_FOR_CLIENTS:8080/hazelcast-mancenter\ -Dhazelcast.instance.name=`hostname`\ -Dpadogrid.workspace=${WORKSPACE_NAME}\ -Dhazelcast.config=/padogrid/etc/hazelcast.xml\ -Dhazelcast-addon.group=myhz\ -Dhazelcast-addon.tcp.port=$SERVER_PORT\ -Dhazelcast.logging.type=log4j2\ -Dlog4j.configurationFile=/padogrid/etc/log4j2.properties\ -Dhazelcast.shutdownhook.enabled=true\ -Dhazelcast.shutdownhook.policy=GRACEFUL\ -Dcom.sun.management.jmxremote.port=$JMX_PORT\ -Dcom.sun.management.jmxremote.ssl=false\ -Dcom.sun.management.jmxremote.authenticate=false\ -Dhazelcast.jmx=true\ -Dhazelcast.health.monitoring.level=NOISY\ -Dhazelcast.health.monitoring.delay.seconds=10\ -Dhazelcast.health.monitoring.threshold.memory.percentage=70\ -Dhazelcast.health.monitoring.threshold.cpu.percentage=70\ -Dhazelcast.diagnostics.enabled=true\ -Dhazelcast.diagnostics.metric.distributed.datastructures=true\ -Dhazelcast.diagnostics.metric.level=info\ -Dhazelcast.diagnostics.invocation.sample.period.seconds=30\ -Dhazelcast.diagnostics.pending.invocations.period.seconds=30\ -Dhazelcast.diagnostics.slowoperations.period.seconds=30\ -Dhazelcast.diagnostics.storeLatency.period.seconds=60\ -Dhazelcast.diagnostics.filename.prefix=$CLUSTER_NAME\ -Dhazelcast.diagnostics.directory=/padogrid/log\ -Xms1g\ -Xmx1g\ -Xdebug\ -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9101\ -Dhazelcast-addon.tcp.members=$TCP_MEMBERS\ -Dhazelcast.local.publicAddress=$HOSTNAME_FOR_CLIENTS:${HOST_SERVER_PORT}"
      - LOG_FILE=/padogrid/log/${CLUSTER_NAME}-${SERVER_NAME}.log
    image: hazelcast/${IMAGE_NAME}:${VERSION}
    hostname: ${SERVER_NAME}
    mem_limit: 1g
    expose:
     - "$SERVER_PORT"
     - "$JMX_PORT"
     - "$DEBUG_PORT"
    ports:
     - "${HOST_SERVER_PORT}:5701"
     - "${HOST_JMX_PORT}:1099"
     - "${HOST_DEBUG_PORT}:9101"
    volumes:
     - ./padogrid:/padogrid/
    restart: on-failure
