version: '2.4'

services:
  mancenter:
    env_file: .env
    image: hazelcast/management-center:${VERSION}
    hostname: mancenter
    mem_limit: 1g
    expose:
     - "$MC_PORT"
    ports:
     - "$MC_PORT:8080"
    volumes:
     - ./padogrid:/padogrid/
