apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service-0
  labels:
    app: hazelcast
    role: hazelcast
    statefulset.kubernetes.io/pod-name: hazelcast-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: hazelcast
    role: hazelcast
    statefulset.kubernetes.io/pod-name: hazelcast-0
  ports:
  - nodePort: 30001
    port: 5701
    protocol: TCP
    targetPort: hazelcast
