apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service-nodeport-0
  labels:
    app: hazelcast
    role: hazelcast
    statefulset.kubernetes.io/pod-name: hazelcast-0
spec:
  type: NodePort
  selector:
    app: hazelcast
    role: hazelcast
    statefulset.kubernetes.io/pod-name: hazelcast-0
  ports:
  - nodePort: 30011
    port: 5701
    protocol: TCP
    targetPort: 5701
