apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: geode-pv-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: geode-pv-claim
    namespace: default
  hostPath:
    path: /data/custom
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
