apiVersion: v1
kind: Template
metadata:
  name: hazelcast
  annotations:
    description: "Openshift deployment template for Hazelcast"
    tags: "hazelcast, imdg, datagrid, inmemory, kvstore, nosql, java"
    iconClass: "icon-java"
labels:
    template: hazelcast-openshift-template

parameters:
- name: HAZELCAST_IMAGE
  description: "Defines the location of Hazelcast image"
  value: registry.connect.redhat.com/hazelcast/hazelcast-4-rhel8:latest
  required: true
- name: SERVICE_NAME
  description: "Defines the service name of the POD to lookup of Kubernetes"
  value: hazelcast-service
  required: true
- name: NAMESPACE
  description: "Defines the namespace (project name) of the application POD of Kubernetes"
  required: false
- name: HAZELCAST_REPLICAS
  description: "Number of Hazelcast members"
  value : "2"
  required: true
- name: ENTERPRISE_LICENSE_KEY
  description: "Defines Hazelcast Enterprise License Key, please enter your License"
  required": true
- name: MANAGEMENT_CENTER_IMAGE
  description: "Defines the location of Hazelcast Management Center image"
  value: registry.connect.redhat.com/hazelcast/management-center-4-rhel8:latest
  required: true
- name: MANAGEMENT_CENTER_SERVICE_NAME
  description: "Defines the service name of Management Center"
  value: management-center-service
  required: true

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hazelcast-configuration
  data:
    hazelcast.yaml: |-
      hazelcast:
        network:
          join:
            multicast:
              enabled: false
            kubernetes:
              enabled: true
          rest-api:
            enabled: true
            endpoint-groups:
              HEALTH_CHECK:
                enabled: true
                
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: local
      app: hazelcast
    name: hazelcast-pv-volume
  spec:
    accessModes:
      - ReadWriteOnce
      - ReadWriteMany
      - ReadOnlyMany
    capacity:
      storage: 2Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: hazelcast-pv-claim
      namespace: ${NAMESPACE}
    hostPath:
      path: /var/lib/minishift/pv/data/custom
    persistentVolumeReclaimPolicy: Retain
    storageClassName: custom
    volumeMode: Filesystem

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: hazelcast
    name: hazelcast-pv-claim
    namespace: ${NAMESPACE}
  spec:
    accessModes:
      - ReadWriteOnce
      - ReadWriteMany
      - ReadOnlyMany
    resources:
      requests:
        storage: 2Gi
    storageClassName: custom
    volumeMode: Filesystem
    volumeName: hazelcast-pv-volume

- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: hazelcast
    labels:
      app: hazelcast
  spec:
    replicas: ${HAZELCAST_REPLICAS}
    selector:
      matchLabels:
        app: hazelcast
        role: hazelcast
    template:
      metadata:
        labels:
          app: hazelcast
          role: hazelcast
      spec:
        containers:
        - name: hazelcast-openshift
          image: ${HAZELCAST_IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
          - name: hazelcast
            containerPort: 5701
          livenessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          resources:
            limits:
              cpu: 200m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - name: hazelcast-storage
            mountPath: /data/hazelcast
          - name: hazelcast-custom
            mountPath: /data/custom
          env:
          - name: HAZELCAST_KUBERNETES_SERVICE_DNS
            value: ${SERVICE_NAME}.${NAMESPACE}.svc.cluster.local
          - name: HZ_LICENSE_KEY
            value: ${ENTERPRISE_LICENSE_KEY}
          - name: HZ_DATA
            value: /data/hazelcast
          - name: JAVA_OPTS
            value: -Dhazelcast.rest.enabled=true -Dhazelcast.config=/data/custom/etc/hazelcast.xml
              -Dnamespace=${NAMESPACE} 
              -Dhazelcast.ssl=false -Dhazelcast.hotRestart=false 
              -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true
              -Dhazelcast.graceful.shutdown.max.wait=600  -Dhazelcast.cluster.version.auto.upgrade.enabled=true
              -Dhazelcast.jmx=true -cp /opt/hazelcast/*:/opt/hazelcast/lib/*:/data/custom/plugins/v1/*
              -Dcom.sun.management.jmxremote.port=12000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dhazelcast.jmx=true
        volumes:
        - name: hazelcast-storage
          configMap:
            name: hazelcast-configuration
        - name: hazelcast-custom
          persistentVolumeClaim:
            claimName: hazelcast-pv-claim

- apiVersion: v1
  kind: Service
  metadata:
    name: ${SERVICE_NAME}
  spec:
    type: LoadBalancer
    selector:
      app: hazelcast
      role: hazelcast
    ports:
    - protocol: TCP
      port: 5701
      nodePort: 30000

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: management-center-volume
  spec:
    selector:
      app: hazelcast
      role: hazelcast
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: management-center
    labels:
      app: hazelcast
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hazelcast
        role: mancenter
    template:
      metadata:
        labels:
          app: hazelcast
          role: mancenter
      spec:
        containers:
        - name: management-center
          image: ${MANAGEMENT_CENTER_IMAGE}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          ports:
          - name: mancenter
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
          - name: mancenter-storage
            mountPath: /data
          env:
          - name: MC_INIT_CMD
            value: "./mc-conf.sh cluster add -H /data -cn dev -ma ${SERVICE_NAME}.${NAMESPACE}.svc.cluster.local"
        volumes:
        - name: mancenter-storage
          persistentVolumeClaim:
            claimName: management-center-volume

- apiVersion: v1
  kind: Service
  metadata:
    name: ${MANAGEMENT_CENTER_SERVICE_NAME}
  spec:
    type: ClusterIP
    clusterIP: None
    selector:
      app: hazelcast
      role: mancenter
    ports:
    - protocol: TCP
      port: 8080
