apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
  name: my-release-hazelcast-enterprise-mancenter
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mancenterport
    nodePort: 31000
    port: 8080
    protocol: TCP
    targetPort: mancenter
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
    role: mancenter
  sessionAffinity: None
  type: LoadBalancer
