apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
    app: my-service
  name: my-service-mc
  namespace: default
spec:
  ports:
  - protocol: TCP
    # nodePort - a static port assigned on each the node
    nodePort: 30011
    # port - port exposed internally in the cluster
    port: 8080
    # targetPort - the container port to send requests to
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
    role: mancenter
  type: NodePort
