apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-release
    role: hazelcast
    statefulset.kubernetes.io/pod-name: my-release-hazelcast-enterprise-0
  name: my-service-0
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 5701
    protocol: TCP
    targetPort: hazelcast
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
    role: hazelcast
    statefulset.kubernetes.io/pod-name: my-release-hazelcast-enterprise-0
  sessionAffinity: None
  type: LoadBalancer
