apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
  name: my-service-lb
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: clusterport
    nodePort: 30010
    port: 5701
    protocol: TCP
    targetPort: hazelcast
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
    role: hazelcast
  sessionAffinity: None
  type: LoadBalancer
