apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
  name: my-release-hazelcast-enterprise
  namespace: default
spec:
  ports:
  - name: hzport
    port: 5701
    protocol: TCP
    targetPort: hazelcast
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: hazelcast-enterprise
    role: hazelcast
  sessionAffinity: None
  type: ClusterIP
