apiVersion: v1  
kind: Service  
metadata:  
  name: hazelcast-service-nodeport
spec:  
  type: NodePort
  selector:  
    app: hazelcast  
    role: hazelcast  
  ports:  
  - protocol: TCP  
    port: 5701  
    targetPort: 5701
    nodePort: 30010

