apiVersion: v1  
kind: Service  
metadata:  
  name: hazelcast-service-lb
spec:  
  type: LoadBalancer  
  selector:  
    app: hazelcast  
    role: hazelcast  
  ports:  
  - protocol: TCP  
    port: 5701  
    nodePort: 30001  
