name: padogrid-SNAPSHOT Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.6.3' ]
        java: [ '8' ]
        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}

      - name: Prepare Release Notes
        run: echo "*The latest Padogrid binary snapshot without man pages and Coherence support.*" > snapshot-release-notes.md
        shell: bash

      - name: Extract Snapshot Release Notes
        run: sed -n '/.*SNAPSHOT/,/---/p' RELEASE_NOTES.md  | sed -n '/^-/,/$/p' | sed '/^---/d' >> snapshot-release-notes.md
        shell: bash

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: PadoGrid SNAPSHOT
          body_path: snapshot-release-notes.md
          draft: false
          prerelease: false

      - name: Upload Release
        uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_file: "*.tar.gz;*.zip"
          file: "padogrid-deployment/target/assembly/*.tar.gz;padogrid-deployment/target/assembly/*.zip"
          release_id: ${{ steps.create_release.outputs.id }}
          branches: "develop"
          overwrite: true
          verbose: true
