#
# Build and publish PadoGrid snapshot upon RELEASE_NOTES.md push
#
name: padogrid-SNAPSHOT Publish

on:
  push:
    branches:
      - 'develop'
    paths:
      - 'RELEASE_NOTES.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.6.3' ]
        java: [ '8' ]
        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}

      - name: Prepare Release Notes
        run: echo "*The latest Padogrid binary snapshot without man pages and Coherence support.*" > snapshot-release-notes.md
        shell: bash

      - name: Extract Snapshot Release Notes
        run: sed -n '/.*SNAPSHOT/,/---/p' RELEASE_NOTES.md  | sed -n '/^-/,/$/p' | sed '/^---/d' >> snapshot-release-notes.md
        shell: bash

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Delete Tag/Release - snapshot
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: 'snapshot' # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag/Release - snapshot
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: snapshot
          release_name: 'padogrid-SNAPSHOT'
          body_path: snapshot-release-notes.md

      - name: Upload Release Assets - snapshot
        uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: "develop"
          tag_name: "snapshot"
          delete_file: "*.tar.gz;*.zip"
          file: "padogrid-deployment/target/assembly/*.tar.gz;padogrid-deployment/target/assembly/*.zip"
          overwrite: true
          verbose: false
